const tl = new TimelineMax()

if(window.innerWidth < 992) {
  tl.addLabel("startAnimation")
  .from(".navigation__envelopeIcon", {y:"-20", duration: 1, ease:"Expo.easeOut", opacity: 0,})
  .from(".navigation__logoBox", {y:"-20", duration: 1, ease:"Expo.easeOut", opacity: 0, delay: 0.2}, "startAnimation")
  .from(".navigation__menuBox", {y:"-20", duration: 1, ease:"Expo.easeOut", opacity: 0, delay: 0.4}, "startAnimation")
  .from(".headingOneSpan", {y:"50", duration: 1, ease:"Expo.easeOut", opacity: 0, stagger: 0.1, delay: "-1"})
  .from(".subTitleSpan", {y:"20", duration: 1, ease:"Expo.easeOut", opacity: 0, stagger: 0.1, delay: "-0.8"})
  .from(".navigation__borderNavigation", {scaleX: 0, transformOrigin: "left", duration: 2}, "startAnimation")
  .from(".navigation__envelopeBoxBorder", {height: 0, transformOrigin: "left", duration: 1}, "startAnimation")
  .from(".navigation__menuBoxBorder", {height: 0, transformOrigin: "left", duration: 1}, "startAnimation")
  .from(".header__bottomLineTopRed", {scaleY: 0, transformOrigin: "top", duration: 1, delay: "-0.75"})
  .from(".header__bottomLineTop", {scaleY: 0, transformOrigin: "top", duration: 1, delay: "-1.5"})
  .from(".solutions__bottomLineTop", {scaleY: 0, transformOrigin: "top", duration: 1, delay: "-0.7"})
  .from(".header__bottomLine", {scaleX: 0, transformOrigin: "left", duration: 2}, "startAnimation")
} else if(window.innerWidth > 992) {
  tl.addLabel("startAnimation")
  .from(".navigation__envelopeIcon", {y:"-20", duration: 1, ease:"Expo.easeOut", opacity: 0,})
  .from(".navigation__logoBox", {y:"-20", duration: 1, ease:"Expo.easeOut", opacity: 0, delay: 0.2}, "startAnimation")
  .from(".navigation__menuBox", {y:"-20", duration: 1, ease:"Expo.easeOut", opacity: 0, delay: 0.4}, "startAnimation")
  .from(".headingOneSpan", {y:"50", duration: 1, ease:"Expo.easeOut", opacity: 0, stagger: 0.1, delay: "-1"})
  .from(".subTitleSpan", {y:"20", duration: 1, ease:"Expo.easeOut", opacity: 0, stagger: 0.1, delay: "-0.8"})
  .from(".navigation__borderNavigation", {scaleX: 0, transformOrigin: "left", duration: 2}, "startAnimation")
  .from(".navigation__envelopeBoxBorder", {height: 0, transformOrigin: "left", duration: 1}, "startAnimation")
  .from(".navigation__menuBoxBorder", {height: 0, transformOrigin: "left", duration: 1}, "startAnimation")
  .from(".header__bottomLineTopRed", {scaleY: 0, transformOrigin: "top", duration: 1, delay: "-0.75"})
  .from(".header__bottomLineTop", {scaleY: 0, transformOrigin: "top", duration: 1, delay: "-1.5"})
  .from(".solutions__bottomLineTop", {scaleY: 0, transformOrigin: "top", duration: 1, delay: "-0.7"})
  .from(".header__bottomLine", {scaleX: 0, transformOrigin: "left", duration: 2}, "startAnimation")
}

// tl.addLabel("startAnimation")
//   .from(".navigation__unorderListElement", {y:"-20", duration: 1, ease:"Expo.easeOut", opacity: 0, stagger: 0.1,})
//   .from(".navigation__envelopeIcon", {y:"-20", duration: 1, ease:"Expo.easeOut", opacity: 0, delay: "-0.8"})
//   .from(".headingOneSpan", {y:"50", duration: 1, ease:"Expo.easeOut", opacity: 0, stagger: 0.1, delay: "-1"})
//   .from(".subTitleSpan", {y:"20", duration: 1, ease:"Expo.easeOut", opacity: 0, stagger: 0.1, delay: "-0.8"})
//   .from(".navigation__borderNavigation", {scaleX: 0, transformOrigin: "left", duration: 2}, "startAnimation")
//   .from(".navigation__envelopeBoxBorder", {height: 0, transformOrigin: "left", duration: 100}, "startAnimation")
//   .from(".navigation__menuBoxBorder", {height: 0, transformOrigin: "left", duration: 1}, "startAnimation")
//   .from(".header__bottomLineTopRed", {scaleY: 0, transformOrigin: "top", duration: 1, delay: "-0.75"})
//   .from(".header__bottomLineTop", {scaleY: 0, transformOrigin: "top", duration: 1, delay: "-1.5"})
//   .from(".solutions__bottomLineTop", {scaleY: 0, transformOrigin: "top", duration: 1, delay: "-0.7"})
//   .from(".header__bottomLine", {scaleX: 0, transformOrigin: "left", duration: 2}, "startAnimation")